SmarterApp/RDW_Ingest

README.md, build.gradle, exam-service/build.gradle, exam-service/src/main/java/org/rdw/ingest/web/OAuth2AuthenticationProvider.java, exam-service/src/main/java/org/rdw/ingest/web/OAuth2Properties.java, exam-service/src/main/java/org/rdw/ingest/web/SecurityConfig.java, exam-service/src/main/resources/application.yml, exam-service/src/test/java/org/rdw/ingest/web/ExamControllerTests.java, exam-service/src/test/java/org/rdw/ingest/web/OAuth2PropertiesTest.java, exam-service/src/test/java/org/rdw/ingest/web/TestAppConfig.java
To clarify this: our client (ETS) will use basic auth while we use OpenAM IDP as the authority for user credentials. This is a rudimentary implementation just to make sure it works as expected. 
After a chat with ETS we will decide whether to continue down this route or switch to full oauth2 (where they'd have to know about our OpenAM IDP and get a token).
=> add basic auth using oauth as the auth provider

README.md, exam-processor/src/main/java/org/rdw/ingest/processor/ExamProcessorConfiguration.java, exam-service/src/main/java/org/rdw/ingest/auth/OAuth2AuthenticationProvider.java, exam-service/src/main/java/org/rdw/ingest/auth/OAuth2Properties.java, exam-service/src/main/java/org/rdw/ingest/auth/RdwUser.java, exam-service/src/main/java/org/rdw/ingest/auth/SecurityConfig.java, exam-service/src/main/java/org/rdw/ingest/service/DefaultExamService.java, exam-service/src/main/java/org/rdw/ingest/service/DefaultExamSource.java, exam-service/src/main/java/org/rdw/ingest/service/ExamService.java, exam-service/src/main/java/org/rdw/ingest/service/ExamSource.java, exam-service/src/main/java/org/rdw/ingest/web/ExamController.java, exam-service/src/test/java/org/rdw/ingest/auth/OAuth2PropertiesTests.java, exam-service/src/test/java/org/rdw/ingest/auth/RdwUserTests.java, exam-service/src/test/java/org/rdw/ingest/auth/WithMockRdwUser.java, exam-service/src/test/java/org/rdw/ingest/auth/WithMockRdwUserSecurityContextFactory.java, exam-service/src/test/java/org/rdw/ingest/service/DefaultExamServiceTests.java, exam-service/src/test/java/org/rdw/ingest/service/DefaultExamSourceTests.java, exam-service/src/test/java/org/rdw/ingest/web/ExamControllerTests.java, exam-service/src/test/java/org/rdw/ingest/web/TestAppConfig.java
This catches the content type and authenticated user so additional message headers can be set for exam-payload
=> auth tweaks to preserve tenancy chain and content type

exam-service/src/test/java/org/opentestsystem/rdw/ingest/ExamServiceApplicationTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/auth/OAuth2PropertiesTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/auth/RdwUserTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/model/RdwImportTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultExamServiceTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultExamSourceTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerTest.java
Clearly our instincts are to name test suite classes with single `*Test`, so i've renamed the `*Tests`.
Followed Alla's lead to name any test suite `*IT` if it requires other processes to be running.
NOTE: running integration tests separate from unit tests is not, in my opinion, handled well by the gradle community so, for now, `*Test` and `*IT` suites are all run as part of the `test` phase. When we get to the point of having lots of slow integration tests, we can separate out their execution.
=> make test class naming consistent

exam-service/src/main/java/org/opentestsystem/rdw/ingest/model/ImportStatus.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/model/RdwImport.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryImpl.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultExamService.java, exam-service/src/main/resources/application.sql.yml, exam-service/src/test/java/org/opentestsystem/rdw/ingest/model/RdwImportTest.java, exam-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java
minor tweak to start fleshing out import records, produces import objects like:
`{
"id": 43,
"content": "EXAM",
"contentType": "text/csv",
"digest": "6CECD8358506280DD938608E314F6501",
"status": "INVALID",
"batch": "3C70D4EC0194DCB626E8FAE8C16BF3E3",
"creator": "dwtest@example.com",
"created": {
"nano": 643000000,
"epochSecond": 1488472962
},
"message": "org.beanio.InvalidRecordException: Invalid 'tdsReport' record at line 8\n ==> Invalid 'academicYear':  Type conversion error: Invalid Long value 'NotAYear'"
}`
=> add message to import

docker/docker-compose.yml, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/AuthConfig.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/AuthProviderType.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/AuthProviderTypeCondition.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/LocalAuthenticationProvider.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/OAuth2AuthenticationProvider.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/RdwUser.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java, exam-service/src/main/resources/application.yml, exam-service/src/main/resources/user-info, exam-service/src/test/java/org/opentestsystem/rdw/ingest/web/TestAppConfig.java
I'm not 100% sure of this change and would like thoughts.
What it does is introduce a local auth provider that is instantiated if no other auth provider is configured. This auth provider reads a file to get user credentials. This will allow us to more easily test with arbitrary tenancy chains without having to create users in ART. The obvious downside is that, should this escape into the wild, it would allow somebody to configure a user without having to use ART. We can easily protect against that but it is still a possible security concern ...
=> add local-auth option

common/build.gradle, common/src/main/java/org/opentestsystem/rdw/ingest/status/LocalSystemStatusIndicator.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/StatusMvcEndpoint.java
I'm not at all thrilled with this hack but we need to get the `url` value in the status, but only if the status is being served up from the MVC endpoint. I really don't want to spend a lot of time on this ... thus the hack.
@rcordeau i was in the build file so i made your recommended change. I'm not sure the `bootRun.enabled=false` actually does anything but i left it in.
=> inject url into status

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/CachingTest.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/CachingTestExecutionListener.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AdminConditionRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/CachingTest.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/CompletenessRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/EthnicityRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GenderRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GradeRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ImportRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SchoolRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SubjectRepositoryIT.java
@agorina, submitted for your review. This allows an easy annotation for tests that use implementations that use caching; it clears cache before every test.
I couldn't find a built-in spring thing that does this and this is more surgical than @DirtiesContext.
If you're okay with it, i'll change all the existing ITs and merge it.
=> caching test helper

common/src/main/java/org/opentestsystem/rdw/ingest/model/ImportContent.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/AbstractStatusIndicator.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/ConfigurationStatusIndicator.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/LocalSystemStatusIndicator.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/StatusConfiguration.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/StatusEndpoint.java, common/src/main/java/org/opentestsystem/rdw/ingest/status/StatusIndicator.java, common/src/test/java/org/opentestsystem/rdw/ingest/status/AbstractStatusIndicatorTest.java, common/src/test/java/org/opentestsystem/rdw/ingest/status/LocalSystemStatusIndicatorTest.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepository.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryImpl.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/status/DatabaseStatusIndicator.java, exam-service/src/main/java/org/opentestsystem/rdw/ingest/status/ProvidersIndicator.java, exam-service/src/main/resources/application.sql.yml, exam-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java
A sample of the response:
```
"database": {
"statusText": "Ideal",
"statusRating": 4,
"databaseOperations": [
{
"statusText": "Ideal",
"statusRating": 4,
"schema": "import",
"responseTime": "2ms",
"type": "READ"
},
{
"statusText": "Ideal",
"statusRating": 4,
"schema": "import",
"responseTime": "7ms",
"type": "WRITE"
}
]
},
```
=> add database status indicator, which required a little refactoring

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
The SBAC data model has at least three different sets of field names. To be a bit more forgiving, this adds aliases for a few critical fields.
=> add aliases for examinee attribute/relationship field names

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/RdwUserTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/WithMockRdwUser.java
Based on clarifications from Landon, this makes the tenancy chains more correct, with the entityId matching the level. This is in anticipation of consolidation of the helper classes some time in the future.
=> make tenancy chains more correct

exam-processor/src/main/resources/application.yml, import-service/src/main/resources/application.yml, package-processor/src/main/resources/application.yml
After my Aurora experiments i felt that these services do not need a big pool of connections lying around. They aren't really web services (yeah, they have API end-points but their primary use case is not serving thousands of users). They don't spawn tons of worker threads; parallelization will happen via multiple instances of the apps, not internal threading.
The default values for pool are 10/100 (initial:10, max:100). To get the absolute optimum settings we'll need to monitor the apps under production-like pressure.
Thoughts?
=> reduce number of connections in pool

import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportSource.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/ImportService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/ImportSource.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportSourceTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerTest.java
This is just a quick change so i can easily resubmit imports that get stuck in ACCEPTED state. That will (currently) happen under two conditions (both will be fixed but for now...):
1. There are no processors running so the rabbit queue has not been created
2. A processor was brought online with items in the queue; it seems to grab a couple and do nothing with them.
This hook can also be used to resubmit in the future when exams are "parked" because the assessment packages aren't available yet.
=> add resubmit hook

migrate-reporting/build.gradle, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Reporting.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/ReportingMigrateJobIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/SpringBatchIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/SpringBatchStepIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/ReportingIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseIT.java, migrate-reporting/src/test/resources/application-test.yml
This sets a framework for the batch and steps IT. All the code is just to show how it will/should be done. 
Since spring batch has its own transaction management, I was not able to find a way to make the transactions roll back at the end of the tests. This means that after Batch ITs execution, all three databases that have 'write' data will have the data in them: spring_batch_reporting, reporting, and staging.   Since we clean up the dbs before each IT run, and since Reporting ITs are not affected by this project, I do not think it is a big problem. Please let me know if you disagree.
=> Added batch integration tests.

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/StagingToReportingStepsConfig.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Warehouse.java, migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/ReportingMigrateJobIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/StagingToReportingStepsConfigIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/DeleteEntitiesIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertOrganizationIT.java, migrate-reporting/src/test/resources/MigrateEntitiesFromStagingForDeleteSetup.sql, migrate-reporting/src/test/resources/MigrateEntitiesFromStagingSetup.sql, migrate-reporting/src/test/resources/MigrateEntitiesFromStagingTierDown.sql, migrate-reporting/src/test/resources/MigrateEntitiesPreloadReportingSetup.sql
The flow (at least for now) is to handle all the 'delete' first, and then process updates/inserts.
This adds the 'delete' all entities step and a step to update/insert School and Districts.
The tests for 'delete' is not completed, because I was lazy to load all the data. I am going to keep adding to that test as more migration is done.
=> Remove all entities and upsertOrganizations.

common/src/main/java/org/opentestsystem/rdw/ingest/common/model/ImportContent.java, import-service/API.md, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/AccommodationController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ImportController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ImportResourceAssembler.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/PackageController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ScopedImportController.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/AccommodationsControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ImportControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ImportResourceAssemblerTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/PackageControllerIT.java
Please vote on this change. 
The import service has evolved as more import tasks have been added. The end-points for getting the import resources included the `content` (e.g. EXAM, PACKAGE). That is odd since the import doesn't really care what content it represents. So, this patch changes the URL for those end-points that don't care about content. For example, all these go away:
```
GET ./exams/imports/{id}
GET ./packages/imports/{id}/payload
GET ./accommodations/imports/{id}/payload/properties
```
and get replaced with the generic end-points:
```
GET ./imports/{id}
GET ./imports/{id}/payload
GET ./imports/{id}/payload/properties
```
=> change imports end-points

common/src/main/java/org/opentestsystem/rdw/ingest/common/model/ImportContent.java, common/src/test/java/org/opentestsystem/rdw/ingest/common/model/ImportContentTest.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/OrganizationController.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/AccommodationControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/OrganizationControllerIT.java
I believe the organization data needs to be processed all at once so i created a single end-point / import content. The alternative would be to have DISTRICT, SCHOOL, etc. but then there would be order-of-operation and resolution problems.
=> add organizations end-points

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/StubbedOutAssessmentRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/StudentGroupRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStubbedOutAssessmentRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentGroupRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AssessmentService.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentService.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessor.java, exam-processor/src/main/resources/application.sql.yml, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentGroupRepositoryIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorTest.java, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/main/resources/application.yml, migrate-reporting/src/test/resources/ImportContentSetup.sql, migrate-reporting/src/test/resources/ImportContentTeardown.sql, migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql, migrate-reporting/src/test/resources/WarehouseEntitiesTearDown.sql
This PR fixes the above mentioned issues, but while testing it I found more problems.
Migrating at the same time as the Import is running fails. After researching it a little bit further I know the following facts:
1. When migrate started it found only one record to migrate with **import id 1** and content CODE. **We preload this record when the schema is created**.
2. It was immediately migrated and then the migrate process went to sleep for 3 minutes while import was running.
4. After the migrate woke up, it ran a few batches of import ids and failed between import id 4000-5000.  
5. The failure was while moving exams due to missing assessment in the reporting DB.
6. I found that the reporting was missing assessments with ids 1-4 (at least).  
What is interesting and puzzling is that …
=> Fix for DWR-392 Migration failure with student groups and sample data

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/status/MigrateReportingJobStatusIndicator.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/status/MigrateReportingJobStatusIndicatorTest.java
This moves the "lifecycle" status to level 0. Why? It is cheap, i.e. just reflecting state which is in memory; it is useful to know that the service is running/enabled. Response looks like this:
```json
{
"statusText": "Warning",
"statusRating": 2,
"level": 0,
"dateTime": "2017-06-12T15:29:46.964+0000",
"migrate-reporting-job": {
"statusText": "Warning",
"statusRating": 2,
"lifecycle": "running,disabled"
}
}
```
=> migrate-status

README.md, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java, migrate-reporting/src/test/resources/MigrateEntitiesFromStagingSetup.sql, migrate-reporting/src/test/resources/MigrateEntitiesFromStagingTearDown.sql
This will affect everybody, so PLEASE read.
MySQL 5.6 has this very strange default setting that causes the NULL timestamp to be automatically replaced with the current timestamp: https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp
Aurora does not have this problem.
In order to have the right configuration you will need to configure your local mySQL.
@rcordeau , I will need your help with configuring CI too.
=> Fix the issues with mySQL timestamp defaulting the current timestamp

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/SqlCopyExecutionStep.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/ReportingMigrateJobIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java, migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql, migrate-reporting/src/test/resources/WarehouseEntitiesTearDown.sql
This fixes the issue for the newly loaded data.
I am not sure what to do with the already loaded data. 
Options I see:
1. write a SQL script to clean them up in the reporting. 
2. write a SQL script to mark them as 'deleted' in the warehouse and expect migrate to clean them up. This way we could also test the migrate/delete. The risk is that if it fails - we will have more issues to deal with.
3. do nothing. I think the 'data generator' data do not have unscored IABs( @malaffoon, please correct me if needed). ETS loaded data do have this problem. If this is the case, would it be easier to load ETS data?
Please let me know what you think.
=> Fix for DWR-456: Un-scored TRT should not be migrated

build.gradle, common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcSchoolRepository.java, common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/SchoolRepository.java, common/src/main/resources/application.sql.yml, migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/CalpadsSchoolsParser.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultOrganizationProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/JsonOrganizationParser.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/OrganizationParser.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/CalpadsSchoolsParserTest.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/JsonOrganizationParserTest.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/OrganizationParserTest.java, package-processor/src/test/resources/CA_schools.baddata.csv, package-processor/src/test/resources/CA_schools.csv, package-processor/src/test/resources/organization.xml
DWR-542 isn't actually the correct ticket for this but that one was under-estimated and we didn't know about this work ...
Since we no longer create stub school/district on TRT import, we needed to get the CA schools into the system. Otherwise all the ETS samples would be rejected as UNKNOWN_SCHOOL. ETS provided us a CALPADS drop so i added a parser for that.
I've updated the PR with performance improvements; they require the latest schema so i'll have another patch to bump the dependency once that is available.
=> add CALPADS schools CSV parsing

build.gradle, docker/docker-compose.yml, task-service/build.gradle, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportConfiguration.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/UpdateOrganizationsConfiguration.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/ArtClient.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/ReconciliationService.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/ReportSender.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ArchiveReportSender.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/DefaultReconciliationService.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/DefaultUpdateOrganizationsService.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/FtpReportSender.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/LoggingReportSender.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/RestImportServiceClient.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/status/ReconciliationReportStatusIndicator.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/status/UpdateOrganizationsStatusIndicator.java, task-service/src/main/resources/application.yml, task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportConfigurationIT.java, task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ReconciliationServiceTest.java, task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/status/ReconciliationReportStatusIndicatorTest.java, task-service/src/test/resources/application-report.yml
The idea is to have multiple senders for a single reconciliation report. This allows the report to be sent to ETS via FTP and to SB Ops via S3 archive.
=> add multiple senders

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorConfiguration.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AccommodationsProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ImportPayloadProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentPackageProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultOrganizationProcessor.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorConfigurationTest.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessorIT.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessorTest.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentPackageProcessorIT.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/OrganizationParserTest.java
@agorina made a comment yesterday about having useful status messages in the database for group loading. That made me think that it would be nice to preserve import messages for successes as well as failures. This is a start on that. 
Opinions?
=> add import message on success

exam-processor/src/main/resources/application.yml, exam-processor/src/test/resources/application-test.yml, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/main/resources/application.yml, migrate-reporting/src/test/resources/application-test.yml, package-processor/src/main/resources/application.yml, package-processor/src/test/resources/application-test.yml
Thanks @jtreuting!
With this change a single insert of 300 records dropped from 12 s. to 75.90 ms.
Here is more info: https://stackoverflow.com/questions/26307760/mysql-and-jdbc-with-rewritebatchedstatements-true
There are some concerns about using this flag ( I assume this is why it is not enabled by default), but I do not think it affects us. 
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html#rewriteBatchedStatements 
I tested by migrating from AWS ETS to my local reporting, here are the stats:
select count(*) from exam; -- 420,571
select timestampdiff(SECOND,min(created), max(updated)) from reporting.migrate
-- 2495 seconds (41 min)  = 168 per second
NOTE: I did not update all the connections, just those that use ```batchUpdate``` call. …
=> DWR-519 Perf: migrate performance

migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/main/resources/application.yml, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java
A previous approach made the migrate process 3 times slower. 
I guess it is a good coincidence that I was testing performance and had 'before the change' times captured. This bring it back to what it was before.
=> DWR-569 fix performance issues

import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/JdbcRdwImportRepository.java, import-service/src/main/resources/application.sql.yml, import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateJobParameters.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateJobParamsTest.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcWarehouseImportRepositoryIT.java
Every day is a learning opportunity ...
Apparently java 8 Instant supports nanosecond precision but the clock that generates instants does not. So, this change lets the database do all the timestamp creation while the java code merely passes the values around. Oh yeah, and Date doesn't even support microseconds so let's avoid that.
=> don't expect java 8 clock to support microseconds

build.gradle
The way things are, JAVA_OPTS are not actually being honored by the container. This change at least gives a reasonable default heap size for Spring Boot apps.
I will be changing the kubernetes configuration in a separate review.
=> default heap size to be a lot smaller

exam-processor/src/main/resources/application.yml, migrate-reporting/src/main/resources/application.yml, package-processor/src/main/resources/application.yml, task-service/src/main/resources/application.yml
Near as i can tell, for apps that have both a real endpoint and management endpoints, the same tomcat connection/thread management is shared. So i left import-service alone.
=> reduce connections/threads for apps that only have management end-points

task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/JdbcReportRepository.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/ReportRepository.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/DefaultReconciliationService.java, task-service/src/main/resources/application.sql.yml, task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/repository/JdbcReportRepositoryIT.java, task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ReconciliationServiceTest.java
when i was in there investigating an "unprocessed import" report, i noticed that we're counting imports when we really just need to check that at least one exists. And we know that counting things is a really bad idea.
=> clean up; use exists instead of count

build.gradle, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorApplication.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/ProcessingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingUserImportService.java, group-processor/src/main/resources/application.sql.yml, group-processor/src/main/resources/application.yml, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/RepositoryBackedConfig.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/RepositoryBackedIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportServiceIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingReferenceServiceIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingStandardizationServiceIT.java, group-processor/src/test/resources/WarehouseEntitiesSetup.sql, group-processor/src/test/resources/WarehouseGroupImportServiceSetup.sql, group-processor/src/test/resources/WarehouseReferenceServiceSetup.sql, group-processor/src/test/resources/WarehouseUserImportServiceSetup.sql, group-processor/src/test/resources/application-test.yml
This PR is step 2 for ingesting groups.
It follows the same pattern as ingesting group students:
1. stage groups that need to be imported/modified
2. create import records for modified groups, chunked by school
3. make the student_group, user_student_group, and student_group_membership tables match the declarations
4. trigger the import and clean up
=> Add group ingest to the group-processor

group-processor/src/main/resources/application.sql.yml, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportServiceIT.java
This PR updates all groups with their assigned import_id during group processing rather than just groups that have been created, deleted, or had a subject change.
=> DWR-940 Migrate all modified groups

task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportConfiguration.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/UpdateOrganizationsConfiguration.java, task-service/src/main/resources/application.yml
During deployment there were a number of times that i wanted to trigger the tasks to test configuration. I had to resort to changing the configuration file (setting cron to every 5 minutes or something), pushing the config changes, waiting, reverting the config changes. 
This lets a client post to actuator end-points to trigger a task.
=> add actuator end-points for triggering tasks

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/JdbcSchoolBatchRepository.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/SchoolBatchRepository.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/BatchingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/BatchingUserImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/ProcessingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/ProcessingUserImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingUserImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/SchoolBatchingGroupImportService.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/SchoolBatchingUserImportService.java, group-processor/src/main/resources/application.sql.yml, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/repository/JdbcSchoolBatchRepositoryIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessorTest.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportServiceIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingUserImportServiceIT.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/SchoolBatchingUserImportServiceTest.java, group-processor/src/test/resources/WarehouseSchoolBatchRepositorySetup.sql
Previously while processing a group batch upload we were creating:
* An import record per school for processing student creation/modification
* An import record per school for processing group creation/modification
However, each student import for each school had the exact same "updated" timestamp, and each group import for each school had the exact same "updated" timestamp.  This means that although we may only *intend* to process half of the imports, *all* of the student or *all* of the group data would be migrated at once, do to being within the migration start-time/end-time boundaries.
This PR uses java to loop over each school individually, naturally spreading the imports in time and allowing bite-sized migration chunks.
=> DWR-932 Spread group processor imports over time

CONTRIBUTING.md, README.md, build.gradle
The CI process is such that `develop` should have the version number set to what we're working towards, in this case 1.0.0.
I've already bumped common and schema.
Note that i am not resetting the build number cause it really should've been 1.0.0 for a while.
=> working version is 1.0.0

build.gradle
The change is that, if doing a ./gradlew dockerPushImage -Pbuildnumber=RELEASE -Prelease, the -Prelease will force the docker image tag to be a versioned tag, which will not overwrite LATEST in dockerHub, but will create a version of the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/326)
=> modifying how we tag the docker file based on release or not

common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcSchoolRepository.java, exam-processor/src/main/resources/application.yml, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SchoolRepositoryIT.java
Pending the results of the investigation of how much the school cache helps, this simply removes it. The risk of rejecting test results outweighs the performance improvements. At least until the test result volume picks up.
=> remove school caches

group-processor/src/main/resources/application.sql.yml, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportServiceIT.java, group-processor/src/test/resources/WarehouseEntitiesSetup.sql, group-processor/src/test/resources/WarehouseGroupImportServiceSetup.sql
Allow clearing users/students from group with users/students
This PR updates the SQL that detects user/student membership changes for groups to account for empty user/student membership lists in both the existing group and uploaded CSV.
=> DWR-969 Allow adding users/students to group with no users/students

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepository.java
The code before was doing the query into a `List<Map<key,value>>` and then converting that into a `List<MapSqlParameterSource>`. This eliminates that middle collection, converting directly to the parameter sources. Not sure how much it will really reduce memory consumption but it won't hurt.
I wanted to take it a step further, eliminating the collection of results completely. But the mysql driver doesn't support client-side cursors so i found it wasn't actually streaming the results: it collected the entire result set no matter what i did. After reading about it, there is a workaround to that but it involves server-side cursors which uses temporary tables and ... (ugh).
=> slight efficiency improvements

common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcImportRepository.java, common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcSchoolRepository.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorApplication.java
Apparently `gradle bootRun` does some AoP magick that doesn't like components in shared libraries to be non-public.
=> make components in common public so AoP can interact with them properly

API.md, README.md
I've combined the API documentation for all the ingest apps. Apart from the diagnostic end-point, really only the import service has any interesting end-points but it seemed easier to combine them all anyway.
=> add to API documentation

common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcSqlListExecutionRepository.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/DefaultSqlListExecutionRepository.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/JdbcSqlListExecutionRepository.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/RepositoryBackedIT.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcReportingSqlListExecutionRepository.java
There were two implementations that seemed almost identical.
And I will most likely need another one for the aggregate reports migrate. So I have decided to clean it up.
=> Clean up JdbcSqlListExecutionRepository.

build.gradle, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRST.java, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/WarehouseEntitiesSetup.sql
Migrate completed_at timestamp field to olap exam staging and fact schemas.
While performing data validation, there was one issue discovered w.r.t. exporting/importing VARCHAR fields containing commas.  The fix is to tell Aurora to optionally enclose fields in quotes.
=> Fix issues discovered during data validation.

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingApplication.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/SpringBatchIT.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/TestAppConfig.java
These changes make a minor improvement to RST execution speed, but the suite still takes ~15 minutes to run on my local machine.  After sampling CPU usage during one of the tests, it appears that the vast majority of time is spent waiting on Aurora and Redshift.  I'm not sure if that can be sped up at all.  At least, not without a drastic change like switching to a developer-local mock AWS stack: https://github.com/localstack/localstack
=> Reduce RST spring environment overhead

common/src/main/resources/application-ingest-common.yml, exam-processor/src/main/resources/application.yml, package-processor/src/main/resources/application.yml
SbacScoreConfiguration is defined in the `ingest-common` but is used by both `ingest-exam-processor` and `ingest-package-processor`. This refactoring moves the yml settings into one file in the `ingest-common` project.
=> DWR-1092 Refactor application.yml for storing sbac score ranges.

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessor.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorApplication.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorTest.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/ApplicationConfiguration.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorApplication.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/GroupMessageProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupMessageProcessor.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/GroupProcessorTest.java, group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupMessageProcessorTest.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/ApplicationConfiguration.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/ImportServiceApplication.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/ApplicationConfiguration.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingApplication.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/ApplicationConfiguration.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingApplication.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/PackageProcessor.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorApplication.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorTest.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ApplicationConfiguration.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/TaskServiceApplication.java
After looking over Will's shoulder yesterday when he was pushing things around to make IT's work in reporting, it seemed worthwhile to make a similar change in RDW_Ingest: separate the application configuration from the main application class. The test runner will then not see the application configuration unless you explicitly tell it to. That makes the DI in the tests cleaner.
While i was in there i renamed a couple classes that had configuration in their name but aren't. That was left over from using Spring Stream's naming convention for processors and it has been bugging me for months.
=> make application configuration consistent

build.gradle, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
Address and remove todo's in IT around created column
Now that all columns exist in audit table add test that no nulls for at least one actual to audit compare,
has no null in actual to ensure no columns are left off the insert in the trigger.
=> Bump the schema version that has missing column in audit table

build.gradle, common/src/main/java/org/opentestsystem/rdw/ingest/common/config/SbacScoreConfiguration.java, common/src/main/java/org/opentestsystem/rdw/ingest/common/model/EntitySqls.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/configuration/GroupProcessingSqlConfiguration.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/config/MigrateStagingToReportingSqlConfiguration.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/config/MigrateWarehouseToStagingSqlConfiguration.java
I'm not thrilled with this but ...
The customer notices when there are warnings in the log. And there are a bunch of messages regarding beans with java validation annotations that don't have the `@Validate` annotation to go with them. I tried the obvious: added `@Validate` annotation. But then tests started failing and the running applications wouldn't start up due to validation failures. So, near as i can tell, the java validation annotations were never being honored. I couldn't get things working properly in my self-imposed time box of 4 hours so i decided to just remove the annotations.
If we ever get some free time perhaps we can revisit this to figure out how to convince Spring to do what we want here. I'm sure there's a way, just kind of fed up with it.
=> fix warnings about non-validated beans

build.gradle, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/step/OlapReportingMigrateStepsConfig.java, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertAsmtsStepRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertFactExamsRST.java, migrate-olap/src/test/resources/OlapAndStagingEntitiesTeardown.sql, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/WarehouseEntitiesSetup.sql, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java
Just to explain the approach:
In order to find the latest exams, the logic I am applying is:
1. Find the latest exam in the staging table and mark it as such.
2. Find an overlap between the found latest exams in staging and in the fact table using [student_id, asmt_id and exam school_year], and updated the found matches, but only if the latest in staging is AFTER the one in the fact table OR it is exactly the same exam.
3. Insert new exams. To find new exams, instead of using LEFT JOIN by exam id, LEFT JOIN by [student_id, asmt_id and exam school_year].
While the SQLs for loading the fact table looks overwhelmingly complex, the execution time has not changed that much.  The load from AWS dev was 1 min longer, 63 min total; the average time for upsertFactStudentExamStep changed from 5.6316 …
=> DWR-1215 Olap migrate loads the latest exam per student/asmt/year combination.

build.gradle, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/step/OlapReportingMigrateStepsConfig.java, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadEmbargoRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpdateEmbargoRST.java, migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
I think that state aggregate queries could benefit from this flag. If not, we can remove it then.
=> Added state embargo to olap migrate

build.gradle, migrate-common/src/main/resources/application.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadEmbargoRST.java, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageEmbargoIT.java
The very first solution had a SQL (that I returned back), then I introduced a view to share the logic between two migrates. The view was not doing exactly what the SQL did. This put the query into a shared SQL file.
=> DWR-1294 Fix to embargo migration

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/DataSourceConfiguration.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/JdbcRetryConfiguration.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentGroupRepository.java, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentRepository.java, exam-processor/src/main/resources/application.yml
We were loading both the RetryConfiguration and a JdbcRetryConfiguration (which extends RetryConfiguration.)  This was causing Spring to set two cutpoints on @Retryable-annotated methods leading to nested retries.
This fix removes the @EnableRetry annotation in favor of loading only the JdbcRetryConfiguration.  
This lead to failures in the MultiThreadedApplicationTest.  We were running 10 threads updating the same data simultaneously with a static backoff of X milliseconds and 4 retries.  Every X milliseconds 1 or 2 executions would complete successfully while the others failed due to transaction conflicts.  16 attempts allowed all 10 threads to complete eventually, 4 attempts did not.
To fix the issue I changed the backoff to an exponential backoff with randomized wait times to spread …
=> Prevent loading both a JdbcRetryConfiguration and RetryConfiguration

docker/docker-compose.yml, import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/JdbcRdwImportRepository.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepository.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java, import-service/src/main/resources/application.sql.yml, import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentParser.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorTest.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentParserIT.java, package-processor/src/test/resources/IAB_ICA_Combined.items.emptyrows.csv
* The tabulator output often produces trailing empty records rows that are just a bunch of field delimiters ... the processor would fail which seems a little extreme.
* We've talked about allowing comments in our CSV.
* Import payloads submitted to the wrong end-point were causing bad duplicate detection. For example, if i accidentally post a package payload to the exams end-point, it properly fails to load anything. But then if i try to post the same payload to the packages end-point, it claims it is a duplicate payload.
=> fix a couple bugs when importing packages

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcPercentileRepository.java, package-processor/src/main/resources/application.sql.yml, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcPercentileRepositoryIT.java
The percentile date range is intended to be inclusive on both ends. So 9/1/2017 - 12/31/2017, 1/1/2018 - 3/31/2018. The query was not detecting overlaps of one day.
@chdietz i'm tagging you here just to verify my supposition above. Thanks.
=> fix a bug detecting overlap

migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateJobRunner.java, migrate-common/src/main/resources/application.sql.yml, migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/MigrateJobRunnerTest.java
We want the migrate job runner to run as long as it has full batches, and then one more partial batch to catch any stragglers. But then it shouldn't continue processing partial batches because that would defeat the purpose of batching things as it processes exams as they trickle in.
The previous incarnation was a bit more complicated than it had to be. Admittedly, this does change the behavior a bit: every run will do a partial batch on the last iteration where before it would only do a partial batch on the first iteration.
=> refine stopping condition for migrate job runner

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedStudentExamWriter.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedStudentGroupAddStudent.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedStudentGroupUpsert.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedStudentRepo.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedTest.java
The errors were being lost in all the other log messages.
I also pulled out the common `newRunnable` code.
=> log exceptions as errors instead of info

migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.yml, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/application-redshift.yml
Based on the discussion this morning I have modified migrate to include only exams that have an asmt grade equal to a student enrolled grade.
=> Modified migrate to not use an explicit accountability grade for HS.

build.gradle
In our run book and troubleshooting docs we often suggest hitting a service's actuator end-points. This requires either port-forwarding or exec'ing into the pod, e.g.
```
$ kubectl exec -it import-service-xxx /bin/sh
```
This is a bit tedious. If curl were in the image, then the instructions become simpler and less error-prone:
```
$ kubectl exec -it import-service-xxx curl http://localhost:8008/env | jq
```
This change adds about 3.5MB to the image (e.g. 113MB -> 117MB), although about half of that is the apk update which i could remove. That is, "apk add -U ..." vs. "apk add ..."
Thoughts?
=> add curl and jq to image

build.gradle, import-service/build.gradle, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/AuthorityService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/CachingPermissionService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/DefaultAuthorityService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SbacTokenConverter.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SbacUser.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SbacUserDetails.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfiguration.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/StubPermissionService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/StubSecurityConfiguration.java, import-service/src/main/resources/application.yml, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/CachingPermissionServiceIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/SbacTokenConverterTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/SbacUserTest.java
I'm trying to keep the PR's small so this just adds authorities to the security model. Still not really populating the permissions that will be needed for group file validation.
There is some functionality that is now common between ingest and reporting. For now, i'm not moving everything into RDW_Common, but i am thinking about parts of it.
=> add Authority awareness to import service security

import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/DefaultAuthorityService.java, import-service/src/main/resources/application.yml
The import service auth mechanism checks the client id *if it is set*. In all but the production environment the client id is not likely to be sensical so i think it is better to default it to blank.
=> default the client id to blank

common/src/main/java/org/opentestsystem/rdw/ingest/common/model/RdwImport.java, common/src/test/java/org/opentestsystem/rdw/ingest/common/model/RdwImportTest.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupMessageProcessor.java, import-service/build.gradle, import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/JdbcRdwImportRepository.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepository.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DuplicateContentAction.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/ImportService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/GroupController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ImportController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ScopedImportController.java, import-service/src/main/resources/application.sql.yml, import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/status/DatabaseStatusIndicatorTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/AccommodationControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/GroupControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ImportControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/NormsControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/OrganizationControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/PackageControllerIT.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ScopedControllerTestSuite.java
Group processing needs to reprocess duplicate payloads instead of ignoring them because there are other things that could affect processing other than just the content (e.g. permissions, organizations). While adding this capability, i kept finding little things that needed tweaking. So, before continuing on with the main SIS changes (sigh) i thought i'd check this in.
=> add Reprocess/Ignore capability

import-service/src/main/java/org/opentestsystem/rdw/ingest/web/AccommodationController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/GroupController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/NormsController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/OrganizationController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/PackageController.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ScopedImportController.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/GroupControllerIT.java
This is WIP, just checking in because it doesn't hurt anything and i'm trying to avoid a big checkin.
@wtritch if you get a chance can you think about this one, or maybe we can just chat about it tomorrow? The idea is that most import content is handled by pushing the file contents onto the rabbit queue. But because we expect student groups to be large we want to archive it off and post a small message: it will be processed directly from the archive. This lets a controller choose which technique to use.
=> tweak controllers to allow file upload to be processed as either a file or bytes

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupMessageProcessor.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadService.java, group-processor/src/main/resources/application.sql.yml, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/GroupImportService.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepository.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepositoryIT.java
Even with timestamp-smearing, uploading a large group file was resulting in blown memory when staging data. In my basic test, it was creating 280k students and trying to read all those rows into memory during warehouse-to-staging. 
This change switches to a "streaming" approach where it reads/writes data in chunks. Please review with a very critical eye since this is a non-trivial change.
=> use a streaming copy for migrate

common/src/main/java/org/opentestsystem/rdw/ingest/common/util/ParserHelper.java, common/src/test/java/org/opentestsystem/rdw/ingest/common/util/ParserHelperTest.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java
The parser helper has a helper function to parse dates. It requires the format to be ISO-8601 whatever. It uses the LocalDate parse exception message which is a bit cryptic, something like `"Text \u00278/1/17\u0027 could not be parsed at index 0"`. Since this is the third or fourth time i've stared at the message and wondered what `\u0027` is and confused `index 0` for the line offset (it's really the field text offset) i thought i'd clean it up. It now emits something like `"invalid date [8/1/17], use format YYYY-MM-DD"`.
Since this is a teeny change, i'll commit and address any concerns raised.
=> improve message for bad date

CONTRIBUTING.md
I scanned all the logger output and don't see any violations. The only thing that is close is that TRTs errors for examinee fields (e.g. name) are captured and stored in the database. But that is okay because database access requires separate credentials and can be protected.
=> add blurb about PII

migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateJobRunner.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateLifecycle.java, migrate-olap/build.gradle, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRunner.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/RunOnStartup.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingJobRunner.java
I'm not 100% sure that this is the best practice approach to this problem. I did play with another approach where i made the TaskExecutor for the JobLauncher a SimpleAsyncTaskExecutor. My concern with that approach is that the JobLauncher will return right away and any scheduling will not take into account when the job actually completes. Since the sole purpose of the migrate apps is to run this one job, it seemed wrong somehow to use an async executor way down in the innards. 
Anyway, this seems to work and is simpler.
=> async job runner

exam-processor/src/main/resources/application.yml, group-processor/src/main/resources/application.yml, import-service/src/main/resources/application.yml, import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/DataSourceIT.java, import-service/src/test/resources/application-test.yml, migrate-olap/src/main/resources/application.yml, migrate-reporting/src/main/resources/application.yml, package-processor/src/main/resources/application.yml, task-service/src/main/resources/application.yml
Thoughts when doing this:
* connect and validation timeouts should be short, i chose 10s. Could be lower, what do you think?
* query timeout depends on app, either 30s or 120s
* socket timeout needs to be longer than query timeout (or else query won't be aborted), i added 10s to query timeout
=> set timeouts for connect, socket and query

import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/AuthorityService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/service/GroupImportService.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/service/GroupImportServiceTest.java
Found this bug while testing the large student group file upload: the default behavior when resubmitting an import is to read the payload from the archive (S3) and then put it in the message body. But groups don't do that, they just put the digest (archive location) in the message.
=> resubmit-groups

build.gradle, exam-processor/src/test/resources/PreloadCustomSubject.sql, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/WarehouseEntitiesSetup.sql, migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/test/resources/ReportingSubjectSetup.sql, migrate-reporting/src/test/resources/StagingEntitiesSetup.sql, migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/WarehouseSubjectAssessmentType.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcSubjectAssessmentTypeRepository.java, package-processor/src/main/resources/application.sql.yml, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectAssessmentTypeServiceTest.java, package-processor/src/test/resources/LoadTestSubject.sql
Remarkably few code changes but lots of test changes.
=> RP-29, RP-30 add target_report handling, including ingest and migrate.

build.gradle, common/src/main/resources/application.sql.yml, common/src/test/java/org/opentestsystem/rdw/ingest/common/repository/LanguageRepositoryIT.java, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
I think having conditional migration like that is going to be problematic: it allows the client to effectively remove a language without violating the db constraints in the warehouse, which will lead to a db constraint violation in reporting ... bad.
I also added a blurb to the RDW documentation about how to tweak languages: https://github.com/SmarterApp/RDW/blob/develop/docs/Runbook.SystemConfiguration.md#language-codes
=> remove extra languages (and filtering based on display_order)

build.gradle, common/build.gradle, exam-processor/build.gradle, group-processor/build.gradle, import-service/build.gradle, migrate-common/build.gradle, migrate-olap/build.gradle, migrate-reporting/build.gradle, package-processor/build.gradle, task-service/build.gradle
Similar to change in common: Dave had trouble with the repo for propdeps not being available. Since we don't really use the `optional` and `provided` features, it seems prudent to stop trying to get it. Note that we do pull in the spring boot `spring-boot-configuration-processor` using `optional`, so i switched that to `compileOnly` which is morally equivalent. I also pulled that common dependency into the root build file since every module was repeating it.
=> remove propdeps

migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateEndpoint.java, migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/MigrateEndpointTest.java
Missed this corner case: after using the actuator end-point to enable migrate, triggering a migrate using the actuator end-point doesn't work.
=> fix migrate enable to actually enable the job runner 

build.gradle, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/step/OlapReportingMigrateStepsConfig.java, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadEntitiesStepRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/TruncateStageStepRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertSubjectsStepRST.java, migrate-olap/src/test/resources/OlapAndStagingEntitiesTeardown.sql, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesForDeleteSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/WarehouseEntitiesSetup.sql
There are no changes to aggregate reports for alt scores, so there aren't many required changes here. However, i chose to push the subject metadata and i tried to make the staging tables reflect the warehouse schema per our general staging philosophy.
A lot of the changes are tests and their data set up. The real changes are the SQL changes and the migrate configuration.
I've run all the tests multiple times but i admit there is a chance that, when deployed to awsqa, i may have to debug some more.
=> modifications for configurable subjects for migrate-olap

script-common/README.md, script-common/build.gradle, script-common/src/main/groovy/org/opentestsystem/rdw/ingest/script/DSLScriptBase.groovy, script-common/src/test/groovy/org/opentestsystem/rdw/ingest/script/DSLScriptBaseTest.groovy, script-common/src/test/java/org/opentestsystem/rdw/ingest/script/ScriptCompilerTest.java, script-common/src/test/java/org/opentestsystem/rdw/ingest/script/ScriptXmlTest.java, script-common/src/test/resources/sample_xml/TDSReport.iab.2018_AIR_format.xml, script-common/src/test/resources/scripts/exam_script.groovy, script-common/src/test/resources/scripts/exam_script_hybrid.groovy, script-common/src/test/resources/scripts/exam_script_xsl.groovy, script-common/src/test/resources/xsl/exam.xsl, script-common/src/test/resources/xsl/exam_items_only.xsl
This is the first phase toward creating a basic DSL for the script pipeline, and I've included a README.md to demonstrate some samples of how the scripts for XML transformation could be written. I'd appreciate any feedback on the approach and general and more specific design elements. E.g., does it make sense to dynamically add XML methods to the script class or would it be better to have separate base classes based on the type of  input being processed? Also, are there other helper methods that we could add?
=> RP-183: Add XML helper methods to script framework

build.gradle, exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/config/TenantConfiguration.java, group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/configuration/TenantConfiguration.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/multitenant/TenantConfiguration.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/SbacTokenConverterTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/web/TestAppConfig.java, import-service/src/test/resources/application-test.yml, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/TenantConfiguration.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/TenantConfiguration.java, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/configuration/TenantConfiguration.java, task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/TenantConfiguration.java
- Map<TenantKey,Tenant> instead of a List<Tenant>
- simplifies modification of tenant data in git, ties it directly to other tenant configuration
- depends on changes in common
=> make the Tenant instances stored in Tenant Properties a Map

migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateEndpoint.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateJobRunner.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateMvcEndpoint.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/TenantAwareMigrateJobRunner.java, migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/TenantAwareMigrateLifecycle.java, migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/MigrateEndpointTest.java, migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/MigrateJobRunnerTest.java, migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/SimpleMigrateLifecycle.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRunner.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/TestAppConfig.java, migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingJobRunner.java, migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/TestAppConfig.java
Before this fix, POSTing to the /migrate end-point would trigger migration for all tenants. This makes it so you can trigger for just one.
=> RP-466, make migrate job runners more tenant-aware

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRunner.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/SpringAsyncConfiguration.java
Adds event listener to OLAP migration job and serializes calls to this method (scheduled, event triggered, or otherwise called via proxy) so that one must complete before another starts.
=> RP-508: Creating a Sandbox/Tenant must migrate and initialize cached values

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRunner.java
attempted fix for java.lang.IllegalStateException: No value for key [..TenantDynamicRoutingDataSource...] bound to thread
- unable to test this locally, but I don't think it can make things any worse
- plan to deploy and evaluate, if it is worse I will quickly back it out
=> attempted fix for java.lang.IllegalStateException

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapEnvironmentChangeListener.java, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRunner.java
- roll back all changes in MigrateOlapReportingJobRunner
- add event listener that calls in same style as migrate endpoint
=> 2nd attempt at fixing olap error

import-service/build.gradle, import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/auth/OktaJwtHelper.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/auth/OktaTokenServices.java, import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/auth/SecurityConfiguration.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/auth/OktaTokenServicesTest.java, import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/auth/SbacTokenConverterTest.java
Enables validating Okta access tokens based on configuration, while still supporting OpenAM during transition period. Per Jeff Khoury, integration to ART will still use OpenAM for the forseeable future.
=> RP-721: integrate import service OAuth with Okta.

validator/src/main/java/org/opentestsystem/rdw/ingest/validator/service/AssessmentChecker.java, validator/src/test/java/org/opentestsystem/rdw/ingest/validator/service/AssessmentCheckerTest.java, validator/src/test/resources/assessments.dup-name.csv
This adds a validation that the assessment name, e.g. "SBAC-IAB-G8E-Perf-Fubar", is not duplicate across subjects. It is allowed and expected to be duplicated within a subject since the name indicates a year-over-year continuity for IABs.
=> add check that assessment names are not duplicated across subjects

build.gradle, migrate-olap/build.gradle, migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/step/OlapReportingMigrateStepsConfig.java, migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml, migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertFactsRST.java, migrate-olap/src/test/resources/OlapAndStagingEntitiesTeardown.sql, migrate-olap/src/test/resources/OlapEntitiesSetup.sql, migrate-olap/src/test/resources/StagingEntitiesSetup.sql, migrate-olap/src/test/resources/application-redshift.yml, package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectProcessor.java, package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectProcessorTest.java, validator/src/main/java/org/opentestsystem/rdw/ingest/validator/service/DefaultValidator.java, validator/src/test/java/org/opentestsystem/rdw/ingest/validator/service/AssessmentCheckerTest.java, validator/src/test/java/org/opentestsystem/rdw/ingest/validator/service/SubjectCheckerTest.java
Exam alt scores will be stored in a table separate from the overall and claim scores. This makes the migration fairly straightforward.
=> enhance migrate-olap to migrate alt-scores

migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadCodesStepsRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadEmbargoRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractAndLoadEntitiesStepRST.java, migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/ExtractStepRST.java
These three RSTs fail intermittently, complaining about files on s3. I honestly don't think these changes will make much difference but i think it is a much cleaner solution to the setup and teardown for the tests.
=> try to fix flaky RSTs

build.gradle, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java, exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorWithOptionalDataIT.java, exam-processor/src/test/resources/Custom_Subject_ICA.xml, exam-processor/src/test/resources/ICA-score-test.xml, exam-processor/src/test/resources/SBAC-IAB-FIXED-G4M-G-MATH-4.xml, exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-LangVocab-ELA-6.xml, exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-ReadLit-ELA-6.xml, exam-processor/src/test/resources/SBAC-IAB-FIXED-G6M-EE.xml, exam-processor/src/test/resources/SBAC-ICA-FIXED-G4M-COMBINED-2017.xml, exam-processor/src/test/resources/SBAC-ICA-FIXED-G6E-COMBINED-2017.xml, exam-processor/src/test/resources/SBAC-ICA-FIXED-G6M-COMBINED-2017.xml, exam-processor/src/test/resources/TDSReport.iab.2018_AIR_empty_examinee.xml, exam-processor/src/test/resources/TDSReport.iab.2018_AIR_format.xml, exam-processor/src/test/resources/TDSReport.iab.basic.errors.xml, exam-processor/src/test/resources/TDSReport.iab.emptyDataElements.xml, exam-processor/src/test/resources/TDSReport.iab.largeitem.xml, exam-processor/src/test/resources/TDSReport.iab.longdata.basic.error.xml, exam-processor/src/test/resources/TDSReport.iab.noElement.xml, exam-processor/src/test/resources/TDSReport.iab.noStudentElement.xml, exam-processor/src/test/resources/TDSReport.iab.sample.xml, exam-processor/src/test/resources/TDSReport.ica.exam.errors.xml, exam-processor/src/test/resources/TDSReport.ica.sample.xml, exam-processor/src/test/resources/TDSReport.no-examinee.xml, exam-processor/src/test/resources/inferSchool/SBAC-IAB-FIXED-G4M-G-MATH-4-delete.xml, exam-processor/src/test/resources/inferSchool/SBAC-IAB-FIXED-G4M-G-MATH-4-new-oppId-and-date.xml, exam-processor/src/test/resources/inferSchool/SBAC-IAB-FIXED-G4M-G-MATH-4.update.student.xml, exam-processor/src/test/resources/inferSchool/SBAC-IAB-FIXED-G4M-G-MATH-4.xml
A number of tests were broken by a tightening of the schema for TRT XMLs, which was done as a hotfix in Tier 3 support and merged into development. Most of the fixes were just updating the sample TRTs used as test inputs to be compliant with the new schema. In a few cases, the tests themselves had to be updated to conform with the new behavior.
=> Pinned common lib to latest version, fixed tests.
