README.md
build.gradle
exam-service/src/main/java/org/rdw/ingest/model/ImportStatus.java
exam-service/src/main/java/org/rdw/ingest/model/RdwImport.java
exam-service/src/main/java/org/rdw/ingest/service/DefaultExamService.java
exam-service/src/main/java/org/rdw/ingest/service/ExamService.java
exam-service/src/main/java/org/rdw/ingest/web/ExamController.java
exam-service/src/test/java/org/rdw/ingest/model/RdwImportTests.java
exam-service/src/test/java/org/rdw/ingest/service/DefaultExamServiceTests.java
exam-service/src/test/java/org/rdw/ingest/web/ExamControllerTests.java

and some other stuff that i will call out in comments

add RdwImport and change end-points, service, etc.

---

README.md

I know, it is lame - but better than nothing. 
We need to decide if we want to have a separate schema/server for it.

MySQL clean up.

---

build.gradle
exam-service/build.gradle
exam-service/src/main/java/org/rdw/ingest/web/OAuth2AuthenticationProvider.java
exam-service/src/main/java/org/rdw/ingest/web/SecurityConfig.java

fix security hole
apply oauth to only exams end-points

use TenancyChain from utils

---

exam-processor/build.gradle
exam-processor/src/main/java/org/rdw/ingest/processor/ExamProcessorConfiguration.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Accommodation.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/AnyExam.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Assessment.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Claim.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/District.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/ExamClaim.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/ExamItem.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/IabExam.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Identifiable.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/IdentifiableWithNaturalId.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/School.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/Student.java
exam-processor/src/main/java/org/rdw/ingest/processor/model/StudentAttributes.java
exam-processor/src/main/java/org/rdw/ingest/processor/repository/AssessmentRepository.java
exam-processor/src/main/java/org/rdw/ingest/processor/repository/AssessmentTypeRepository.java
exam-processor/src/main/java/org/rdw/ingest/processor/repository/impl/AssessmentRepositoryImpl.java
exam-processor/src/main/java/org/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryImpl.java
exam-processor/src/main/java/org/rdw/ingest/processor/service/AssessmentTypeService.java
exam-processor/src/main/java/org/rdw/ingest/processor/service/ExamProcessor.java
exam-processor/src/main/java/org/rdw/ingest/processor/service/ExamService.java
exam-processor/src/test/java/org/rdw/ingest/processor/ExamProcessorConfigurationTest.java
exam-processor/src/test/java/org/rdw/ingest/processor/configuration/data/AssessmentRepositoryImplIT.java

This is the first draft. Will add unit tests when I add the real functionality.

A first draft of the exam processor model and flow.

---

README.md

This just updates the README to explain how to run mysql in a docker container.

mysql instructions

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/AnyExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/IabExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/AssessmentTypeRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SchoolRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamServiceTestIT.java
exam-processor/src/test/resources/SBAC-IAB-FIXED-G4M-G-MATH-4.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-LangVocab-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-ReadLit-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6M-EE.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G4M-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6E-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6M-COMBINED-2017.xml

Just trying to maintain the size of the review.
More cleanup effort to follow.

One of the multiple clean ups. More to follow.

---

README.md
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorApplication.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfiguration.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/ExamServiceApplication.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/auth/OAuth2AuthenticationProvider.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryImpl.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultExamService.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultExamSource.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java
exam-service/src/main/resources/application.sql.yml
exam-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerTest.java

clean up some TODO's

---

README.md
docker/docker-compose.yml
exam-service/src/main/resources/mapping.xml

Add a docker-compose.yml spec and adjust README.md to use it.
NOTE: this reverts back to a native MySQL instance.

docker-compose

---

README.md
exam-service/build.gradle
exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepository.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryImpl.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultExamService.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultExamSource.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/service/ExamService.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/web/RdwImportResource.java
exam-service/src/main/java/org/opentestsystem/rdw/ingest/web/RdwImportResourceAssembler.java
exam-service/src/main/resources/application.sql.yml
exam-service/src/main/resources/application.yml
exam-service/src/test/java/org/opentestsystem/rdw/ingest/model/ImportStatusTest.java
exam-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java
exam-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultExamServiceTest.java
exam-service/src/test/java/org/opentestsystem/rdw/ingest/web/ExamControllerTest.java

Tweak ObjectMapper to deal with java 8 time, and null values.
Add HATEOAS link to imports.
BEFORE:
```
{
"id": 69,
"content": "EXAM",
"contentType": "application/xml",
"digest": "CEE97BE54F21345CAE7D24CB33A969AF",
"status": "ACCEPTED",
"batch": null,
"creator": "dwtest@example.com",
"created": {
"nano": 797000000,
"epochSecond": 1488572552
},
"message": null
}
```
AFTER:
```
{
"id": 69,
"content": "EXAM",
"contentType": "application/xml",
"digest": "CEE97BE54F21345CAE7D24CB33A969AF",
"status": "ACCEPTED",
"creator": "dwtest@example.com",
"created": "2017-03-03T20:22:32.797Z",
"_links": {
"self": {
"href": "http://localhost:8080/exams/69"
}
}
}
```

flesh out marshaling

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamParser.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ExamineeParser.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ParsedExaminee.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ParsedExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/StudentExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/TDSReportProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeParser.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultParsedExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamParser.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/IabExamParser.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/IabExamProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfigurationTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorTestIT.java

This should support the following validation logic:
1. authorize the user with the given tenancy chain
2. verify that the assessment packages are loaded
3. parsing and codified fields validation

More refactoring in preparation for the different validations.

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Accommodation.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/AnyExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/District.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ParsedExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultParsedExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/utils/ParseUtil.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/model/DistrictTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/model/SchoolTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryImplIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SchoolRepositoryIT.java

This covers unit testing for Model and Repos. I will be working on the Services unit testing next.

Better unit testing.

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/AnyExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Assessment.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamClaim.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/IabExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/StubbedOutAssessmentRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StubbedOutAssessmentRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/IabExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/utils/ParseUtil.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryImplIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/utils/ParseUtilTest.java
exam-processor/src/test/resources/TDSReport.ica.score.errors.xml

Please note that you will need the latest RDW_Schema for this to work.

The primary focus is to support Null for scores.

---

exam-processor/src/test/resources/SBAC-IAB-FIXED-G4M-G-MATH-4.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-LangVocab-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-ReadLit-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6M-EE.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G4M-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6E-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6M-COMBINED-2017.xml
exam-processor/src/test/resources/TDSReport.iab.basic.errors.xml
exam-processor/src/test/resources/TDSReport.iab.sample.xml
exam-processor/src/test/resources/TDSReport.ica.sample.xml
exam-processor/src/test/resources/TDSReport.ica.score.errors.xml

This needs to be coordinated with changes to RDW_Common.

tweaks to match TRT 1.10

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamItem.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/IabExamProcessor.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java
exam-processor/src/test/resources/TDSReport.ica.score.errors.xml

This has a matching RDW_Schema change.

Changed to identify an Item by a String id instead of bank and item keys.

---

import-service/src/main/java/org/opentestsystem/rdw/ingest/service/ArchiveService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/LocalArchiveService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/S3ArchiveService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/status/DatabaseStatusIndicator.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/LocalArchiveServiceTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/S3ArchiveServiceTest.java

I had a dream last night that we'd want properties and contentType was just the tip of the iceberg. So i added this, mostly so properties would be saved.

add properties to ArchiveService

---

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Item.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentPackageRepositoryImpl.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultItemParser.java
package-processor/src/main/resources/application.sql.yml
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/model/ItemTest.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentPackageRepositoryIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/89)

adding in missed max_points for Item

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AdminConditionRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryImplIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/CompletenessRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/EthnicityRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GenderRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GradeRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SchoolRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SubjectRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentPackageRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentTypeRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ClaimRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/DepthOfKnowledgeRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GradeRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/MathPracticeRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/SubjectRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/TargetRepositoryIT.java

While I am not sure I agree that it is a good idea to run IT tests on the Db with the data, since it is not hard to fix, I am okay with this approach for now.
The reason I am not fully buying into this approach: if you do not know what is in the DB, you can run into an unexpected behaviour just because of the data conflict. For example, your test may expect to create a new entry while it may be already there.  I think the better approach would be to have a separate Db for the Integration testing from the one that is used for the functional testing.

Fixed RepositoryIT failure when DB is not empty.

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/AnyExam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryImpl.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/AnyExamProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/IabExamRepositoryIT.java

timestamp cleanup

---

import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryImpl.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ExamController.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/web/RdwImportCsvMessageConverter.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/web/RdwImportReconciliation.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/web/RdwImportCsvMessageConverterTest.java

This started with verifying that the completed_at timestamp was being pulled out properly and consistently. But i tweaked a couple other things. @bgsavage please vet changes, i'll put comments inline.

ongoing timestamp cleanup

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Assessment.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamItemProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java

I incorrectly assumed that TRT's items have to be validated against Asmt Items one to one. 
I was corrected that TRT's items must be a subset of the Asmt items. 
This change addresses it.

Fix to the TRT items validation.

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/StudentRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryImpl.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryIT.java

Due to changes in https://github.com/SmarterApp/RDW_Schema/pull/49

Adjusted Student id to Integer.

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorApplicationIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/ImportServiceApplicationIT.java
migrate-service/src/test/java/org/opentestsystem/rdw/ingest/migrate/MigrateServiceApplicationIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/122)

updating certain tests to be ITs

---

docker/docker-compose.yml
migrate-reporting/build.gradle
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingApplication.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/configuration/DataSourceConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/listener/MigrateJobCompletionListener.java
migrate-reporting/src/main/resources/application.sql.yml
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/main/resources/bootstrap.yml
settings.gradle

Preview: not ready to go.
Initial get spring batch for data mart migration working as a module.
Works with docker.
Sample tasklets to query data warehouse and reporting
Issues:
1. original decision to put batch tables in warehouse may not be a good idea, suggestion is to put where writing.
2. Need to add tests.

initial spring batch for migrate to data mart

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/status/DiagnosticLevel.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/status/DatabaseStatusIndicator.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/status/ProvidersIndicator.java
task-service/build.gradle
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/TaskServiceApplication.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/ImportRepository.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/impl/ImportRepositoryImpl.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/ServiceConfiguration.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/status/MailSenderStatusIndicator.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/status/RepositoryStatusIndicator.java
task-service/src/main/resources/application.yml

Added health endpoints to task-service and two custom status indicators

Add diagnostic endpoints to task-service

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateBatch.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingApplication.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Reporting.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StepTasklet.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Warehouse.java

Next I will work on adding unit testing.

Added an option to pass param between steps.

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/configuration/DataSourceConfiguration.java
migrate-reporting/src/main/resources/application.sql.yml
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/resources/application-test.yml

and have reporting adbc template use batch datasource to use the same transaction manager.
Next step review batch configuration to see if it can be simplified.

Remove reporting datasource 

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/configuration/DataSourceConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/ReportingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcReportingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Reporting.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/TestAppConfig.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/TestDataSourceConfiguration.java

There was two transaction managers. Cleaned it up.

Fixed transaction manager issue.

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/model/ImportContent.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/model/ImportContentTest.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/MigrateCodesFromStagingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcMigrateCodesFromStagingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/MigrateStagingToWarehouseSqlConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/DeleteCodes.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Reporting.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StepTasklet.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertCodes.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/ReportingMigrateJobIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/RepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/SpringBatchIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcMigrateCodesFromStagingRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/ReportingIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertCodesIT.java
migrate-reporting/src/test/resources/MigrateCodesFromStagingSetup.sql
migrate-reporting/src/test/resources/MigrateCodesFromStagingTierDown.sql

This is just a first pass. 
After I talk to @malaffoon I want to consider how the other steps will be done to avoid refactoring later. Because this may change, I did not finish all the tests. Will do once I have a plan defined.

First try at adding codes migration.

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java

change the be an name for a step

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Assessment.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStubbedOutAssessmentRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentService.java
exam-processor/src/main/resources/application.sql.yml

Yeah, i know this is temporary and all.

set asmt name when creating stub assessments

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateBatchId.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/MigrateImportRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcMigrateImportRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/DefaultNextJobService.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/NextJobService.java
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcMigrateImportRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcWarehouseToStageRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/NextJobServiceTest.java
migrate-reporting/src/test/resources/MigrateImportFromWarehouseSetup.sql
migrate-reporting/src/test/resources/MigrateImportFromWarehouseTeardown.sql

1. Added new repo to get id's from warehouse and reporting
2. created object just to hold id's
3. created service that handles logic of id's and build list of id's for next batch job
4. designed to be called before spring batch to simplify job
a. need to move max batch size to properties

Added service, repo and tests for external get id's for job

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/School.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/ExecutionParams.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/Migrate.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateBatch.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/listener/MigrateJobExecutionListener.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/ReportingMigrateRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcReportingMigrateRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StepTasklet.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/Warehouse.java
migrate-reporting/src/main/resources/application.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/listener/MigrateJobExecutionListenerIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcReportingMigrateRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/DeleteCodesIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/DeleteEntitiesIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertCodesIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertOrganizationIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertStudentsAndGroupsIT.java
migrate-reporting/src/test/resources/MigrateImportFromWarehouseSetup.sql

it is addressing a code review comment.

Changes to the migrate to have its own id

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/WarehouseImportRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcWarehouseImportRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/DefaultNextJobParamService.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/NextJobParamsService.java
migrate-reporting/src/main/resources/application.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcWarehouseImportRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/service/DefaultNextJobParamServiceTest.java
migrate-reporting/src/test/resources/MigrateImportFromWarehouseSetup.sql

@agorina you may want to merge your feature/migrate-id first and then I will check for conflicts.
1. updated repo to account for id's not in true sequence
2. modified service to account for repo change

Change service and repository to account for import id not in sequence

---

README.md
task-service/README.md
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ImportServiceClientProperties.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/RestImportServiceClient.java

fix credentials for hitting import service

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/util/DataElementError.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/util/DataElementErrorCollector.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/util/ParserHelper.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/EthnicityService.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/ExamItemProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/AnyExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultEthnicityService.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamItemProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ExamProcessorRegistry.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/IabExamProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/utils/ParseUtil.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/utils/ParseUtilTest.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultItemParser.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/DataElementErrorCollectorTest.java

Goal was to use the collector everywhere. 
Next step would be to have collector contain both errors and warnings.

cleanup error message handling a bit

---

docker/docker-compose.yml

This tweak goes along with some deployment cleanup i'm doing.

remove optional dependency

---

common/src/test/java/org/opentestsystem/rdw/ingest/common/util/ParserHelperTest.java
package-processor/build.gradle
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorApplication.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/status/DatabaseStatusIndicator.java
package-processor/src/main/resources/application.sql.yml
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/status/DatabaseStatusIndicatorTest.java

add status end-point to package-processor

---

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessor.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessorIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAccommodationsProcessorTest.java
package-processor/src/test/resources/AccessibilityConfig.baddata.xml
package-processor/src/test/resources/AccessibilityConfig.badxml.xml
package-processor/src/test/resources/AccessibilityConfig.schema.xml
package-processor/src/test/resources/AccessibilityConfig.xml

I really don't like javax.xml, it has the most un-java-like interfaces. So i couldn't stop myself from pushing code around a bit. If you don't like it, let me know and i can revert some of it. I also added some error checking that wasn't there before. And the tests of course.

add test coverage for accommodations processor

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/StudentGroupRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStubbedOutAssessmentRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentGroupRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentService.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/AssessmentRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StubbedOutAssessmentRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentGroupRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql

Alings the code with https://github.com/SmarterApp/RDW_Schema/pull/82

DWR-398 Modify stubbed data ingest to be safe for parallel processing

---

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentParser.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultItemParser.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/ItemParser.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentParserIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultItemParserIT.java

I am not happy with this, and it should probably be refactored. 
But this gives me all what I need to resolve the tabulator load issues with SBAC.

Modify asmt package loader to report more info with the error.

---

CONTRIBUTING.md
README.md
build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/224)

Build cleanup

---

CONTRIBUTING.md
README.md
build.gradle
exam-processor/build.gradle
gradle.properties
import-service/build.gradle
migrate-reporting/build.gradle
package-processor/build.gradle
task-service/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/230)

build file cleanup and docker credentials

---

build.gradle
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertStudentsAndGroupsIT.java

There are a few SQL that I left unchanged. I am still looking into them.

Changes to the SQL to improve performance.

---

build.gradle
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java

Renamed asmt table claim columns to be consistent with the exam table.

Renamed asmt table claim columns to be consistent with the exam table.

---

migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml

I have made this change based on the comments in https://github.com/SmarterApp/RDW_Ingest/pull/236

Added aliases to tables in SQLs.

---

migrate-reporting/RunBook.md
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml

I am still working on another one for the schema. 
@malaffoon, thank you for your help!.

DWR-448 Documentation: create tips and tricks document

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedStudentExamWriter.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java

Read https://jira.fairwaytech.com/browse/DWR-480 for some details but: this is a field that is in the TRT, and Alla had already added the database field. It is considered optional, and there is no need to migrate it to the data mart.

DWR-480, capture oppId

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Assessment.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamItem.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ItemTrait.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/StudentExamAttributes.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcAccommodationRepository.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultEthnicityServiceTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-LangVocab-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6E-ReadLit-ELA-6.xml
exam-processor/src/test/resources/SBAC-IAB-FIXED-G6M-EE.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G4M-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6E-COMBINED-2017.xml
exam-processor/src/test/resources/SBAC-ICA-FIXED-G6M-COMBINED-2017.xml
exam-processor/src/test/resources/TDSReport.iab.longdata.basic.error.xml
exam-processor/src/test/resources/TDSReport.iab.sample.xml
exam-processor/src/test/resources/TDSReport.ica.exam.errors.xml
exam-processor/src/test/resources/TDSReport.ica.sample.xml

There are still more tests to add. Working on it.

DWR-443 - more clean up and unit tests

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/util/ParserHelper.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/util/Precondition.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/util/CheckNotNullTest.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/util/ParserHelperTest.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/util/PreconditionTest.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java

I think this change completes this JIRA.

DWR-443 - more unit tests

---

migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/test/resources/MigrateEntitiesFromStagingSetup.sql

When a student is create as part of the student group CSV upload, the gender may be null.

DWR-557 Migrate did not migrate a student when gender is null

---

build.gradle
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java
migrate-reporting/src/test/resources/MigrateCodesFromStagingForDeleteSetup.sql
migrate-reporting/src/test/resources/MigrateCodesFromStagingSetup.sql
migrate-reporting/src/test/resources/MigrateCodesPreloadReportingSetup.sql
migrate-reporting/src/test/resources/MigrateEntitiesFromStagingCodesPreloadToReporting.sql
migrate-reporting/src/test/resources/MigrateEntitiesFromStagingSetup.sql
migrate-reporting/src/test/resources/MigrateEntitiesPreloadReportingSetup.sql
migrate-reporting/src/test/resources/ReportingCodesForEntitiesPreload.sql
migrate-reporting/src/test/resources/ReportingCodesPreload.sql
migrate-reporting/src/test/resources/ReportingEntitiesPreload.sql
migrate-reporting/src/test/resources/WarehouseCodesForDeleteSetup.sql
migrate-reporting/src/test/resources/WarehouseCodesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcAssessmentPackageRepositoryIT.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcMathPracticeRepositoryIT.java

DWR-613 Ingest: denormalize dok
DWR-615 Ingest: math_practice is missing a code field

DWR-569 Datamart: add exam.accommodation_codes column

---

build.gradle

There will be a PR for reporting as well, but i'm going to merge this one first to make sure it doesn't muck up the CI.

update version of docker plugin

---

build.gradle
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateJobExecutionListener.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateJobPartitioner.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/SqlCopyWarehouseToStagingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepository.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/SqlCopyAllExecutionStep.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/SqlCopyExecutionStep.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateJobPartitionerTest.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/TestAppConfig.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepositoryIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java
migrate-reporting/src/test/resources/MigrateEntitiesFromStagingSetup.sql

This is not final - just show the approach.
Would like to know what you think about the approach and if we want to implement it.

Feature/dwr 519 - multithread step that moved exams from warehouse to staging

---

build.gradle
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcWarehouseToStageRepositoryIT.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultItemParser.java

add log statement i found useful during debugging

use latest schema

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/JdbcSchoolRepository.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/repository/SchoolRepository.java
common/src/main/resources/application.sql.yml
package-processor/src/main/resources/application.yml
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcSchoolRepositoryIT.java

There was a problem with the rewriteBatchedStatements=true flag and callable statements; it broke the organization import.

fix problem with batch upserting schools

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcItemTraitRepository.java
exam-processor/src/main/resources/application.yml
exam-processor/src/test/resources/application-test.yml
import-service/src/main/resources/application.yml
import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/DataSourceIT.java
import-service/src/test/resources/application-test.yml
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/resources/application-test.yml
package-processor/src/main/resources/application.yml
package-processor/src/test/resources/application-test.yml
task-service/src/main/resources/application.yml
task-service/src/test/resources/application-test.yml

There are similar changes in reporting and in sbac-config-repo.

set client character encoding

---

build.gradle
common/src/main/java/org/opentestsystem/rdw/ingest/common/model/RdwImport.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/model/RdwImportTest.java
exam-processor/src/test/resources/PreloadAsmtAndSchoolData.sql
import-service/API.md
import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/JdbcRdwImportRepository.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepository.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/web/ImportController.java
import-service/src/main/resources/application.sql.yml
import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/web/ImportControllerIT.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/ReportSender.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ArchiveReportSender.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/DefaultReconciliationService.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/FtpReportSender.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/LoggingReportSender.java
task-service/src/main/resources/application.sql.yml
task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/service/impl/ReconciliationServiceTest.java

remove replay_id
changes to match ArchiveService changes (from RDW_Common)

a few random fixes

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfiguration.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfigurationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/303)

updating to support binary message coming across the queue

---

group-processor/src/main/resources/application.sql.yml
group-processor/src/test/resources/WarehouseGroupImportServiceSetup.sql

This PR fixes uploads that register the same user to the same group in multiple rows.
I've also made changes to handle registering the same student to the same group in multiple rows.

DWR-920 fix group uploads with multiple entries for the same user/group

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/JdbcSqlCopyWarehouseToStagingRepository.java
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql

This PR updates our migration scripts to migrate student-membership whenever a group is modified.

DWR-922 Update migration to migrate student membership on group update

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfiguration.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadService.java
group-processor/src/main/resources/application.sql.yml
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfigurationTest.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadServiceIT.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadServiceTest.java
group-processor/src/test/resources/sample-group-001.csv

This PR trims all string values of both spaces and carriage-return characters during the CSV load.

Trim string values during group csv ingest

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfiguration.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/JdbcStudentGroupBatchRepository.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/repository/StudentGroupBatchRepository.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfigurationTest.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/repository/JdbcStudentGroupBatchRepositoryIT.java

Fix a bug where we were modifying Imports as upload batches.

Stop modifying imports as csv upload batches

---

README.md
build.gradle
docker/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smarterapp/rdw_ingest/320)

updating to deploy docker images to new spot in docker hub

---

CHANGELOG.md
build.gradle
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportConfiguration.java
task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportTaskTest.java

I will merge this after approval and smoke testing in awsxxx environment.

fix reconcilation report query evaluation

---

exam-processor/src/main/resources/application.yml
exam-processor/src/test/resources/application-test.yml
group-processor/src/main/resources/application.yml
group-processor/src/test/resources/application-test.yml
import-service/src/main/resources/application.yml
import-service/src/test/resources/application-test.yml
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/DataSourceConfiguration.java
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/TestAppConfig.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/impl/TestWarehouseDataSourceConfiguration.java
migrate-reporting/src/test/resources/application-test.yml
package-processor/src/main/resources/application.yml
package-processor/src/test/resources/application-test.yml
task-service/src/main/resources/application.yml
task-service/src/test/resources/application-test.yml

Sometimes Spring makes things easy ...

use property placeholders for url-schema and url-server

---

migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfig.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageOrganizationsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfigIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertOrganizationIT.java
migrate-reporting/src/test/resources/ReportingAndStagingEntitiesTeardown.sql
migrate-reporting/src/test/resources/ReportingEntitiesSetup.sql
migrate-reporting/src/test/resources/StagingEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesTeardown.sql
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/JsonOrganizationParser.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/JsonOrganizationParserTest.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/OrganizationParserTest.java

district_group and school_group are treated very much like district so this is mostly copy and pasting.

migrate district/school groups (and external id)

---

build.gradle
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/ForgeRockTokenServices.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SbacTokenConverter.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/StubTokenServices.java
import-service/src/main/resources/application.yml
import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/ForgeRockTokenServicesTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/SbacTokenConverterTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/status/TokenServicesStatusIndicatorTest.java

After chatting with Will yesterday, i decided to better check the grant role in the import service. Most of the changes involve bean fiddling.

tighten down data load role

---

build.gradle
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/StudentExamAttributes.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/multithreaded/MultiThreadedTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
group-processor/src/test/resources/WarehouseEntitiesSetup.sql
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java
migrate-reporting/src/test/resources/ReportingAndStagingEntitiesTeardown.sql
migrate-reporting/src/test/resources/StagingEntitiesForDeleteSetup.sql
migrate-reporting/src/test/resources/StagingEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesTeardown.sql
task-service/src/main/resources/application.sql.yml
task-service/src/test/resources/JdbcReportRepositoryITSetup.sql

This PR merges exam_student into exam.  The changes are relatively light since the two tables had a 1-to-1 relationship.

Merge exam_student into exam.

---

CONTRIBUTING.md
README.md
common/src/main/java/org/opentestsystem/rdw/ingest/common/model/ImportStatus.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/repository/JdbcRdwImportRepository.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/repository/RdwImportRepositoryIT.java

As part of testing this i noticed the README needed updating. I also noticed a method in the project i was spot-checking had no coverage, so i added it.

update README regarding coverage

---

migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertAsmtsStepIT.java
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertOrganizationStepIT.java
migrate-olap/src/test/resources/ReportingEntitiesSetup.sql
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java

Two more 'ignored' ITs and two more left to go.

DWR-1060 More integration tests

---

CONTRIBUTING.md
README.md
build.gradle

updated some documentation for building applications

correcting build instructions

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/GroupProcessor.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/ProcessingLoadService.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessor.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadService.java
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessorTest.java

If you look at the jira (https://jira.fairwaytech.com/browse/DWR-1091) this came up when i was diagnosing a problem in production. It would've been a lot nicer to have the SQL exception text in the ImportException message.
Also some unrelated cleanup.

add exception message to import exception

---

CONTRIBUTING.md
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorConfiguration.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/GroupProcessorConfiguration.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultGroupProcessor.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseCheck.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/PackageProcessorConfiguration.java

Just some minor cleanup while i was documenting log messages

make log level consistent

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java

Last one for exam related audit tables.

Add integration test for audit_exam_claim_score

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryIT.java

tests variations of add and delete ethnicity and compares audit records.

Test audit of student ethnicity

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/util/JdbcUtil.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Accommodation.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Assessment.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Item.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/AssessmentPackageRepository.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcAssessmentPackageRepository.java
package-processor/src/main/resources/application.sql.yml
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcAssessmentPackageRepositoryIT.java
package-processor/src/test/resources/PreloadAsmt.sql

This is done in preparation for supporting asmt updates/

DWR-1131 Add findOneByNaturalId to AssessmentPackageRepository 

---

group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingGroupImportServiceIT.java
group-processor/src/test/resources/WarehouseGroupImportServiceSetup.sql

As part of trying to track this down, i created this test. Doesn't really help with the overall issue but i thought i'd preserve it ...

fiddle with student groups with bad years

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorIT.java

Follow-on to https://github.com/SmarterApp/RDW_Schema/pull/189

Increase allowed t3-program-type length from 20 to 30 characters

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorAuditIT.java
exam-processor/src/test/resources/examStudentAudit/trt/B001-SSID001-ICA-030-V01.xml
exam-processor/src/test/resources/examStudentAudit/trt/B002-SSID001-IAB-010-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B002-SSID001-ICA-030-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B004-SSID001-ICA-030-V03.xml
exam-processor/src/test/resources/examStudentAudit/trt/B004-SSID002-IAB-040-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B005-SSID001-ICA-030-V04.xml
exam-processor/src/test/resources/examStudentAudit/trt/B006-SSID001-ICA-060-V01.xml
exam-processor/src/test/resources/examStudentAudit/trt/B006-SSID003-ICA-050-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B007-SSID001-IAB-020-V01.xml

* fix dates on each TRT that is an exam update
* add additional validations on counts of audit tables

Fix dates in TRT dates for updates and extra validations.

---

group-processor/src/main/resources/application.sql.yml

I'd like to push this and try it in awsqa before deploying to production configuration

newline handling

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorAuditIT.java
exam-processor/src/test/resources/examStudentAudit/trt/B001-SSID002-IAB-040-V01.xml
exam-processor/src/test/resources/examStudentAudit/trt/B001-SSID003-ICA-050-V01.xml
exam-processor/src/test/resources/examStudentAudit/trt/B002-SSID001-IAB-010-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B004-SSID001-ICA-030-V03.xml
exam-processor/src/test/resources/examStudentAudit/trt/B004-SSID002-IAB-040-V02.xml
exam-processor/src/test/resources/examStudentAudit/trt/B005-SSID001-ICA-030-V04.xml
exam-processor/src/test/resources/examStudentAudit/trt/B006-SSID003-ICA-050-V02.xml

Additional changes in tests files to support sample queries

Add extra changes and assertions to support sample queries

---

build.gradle
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamItemProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamItemProcessorTest.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/test/resources/ReportingEntitiesSetup.sql

embargo migrate short-term hack

DWR-154 cleanup

---

README.md
build.gradle
migrate-olap/build.gradle
migrate-olap/src/main/resources/application.yml
migrate-olap/src/test/resources/application-redshift.yml

This pushes things around a bit so i can configure the CI build to run RSTs.

clean up RST execution

---

build.gradle
migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml

This change goes with schema change. I'll update the schema dependency when it finishes building and all that ... just wanted to get the review out.

redshift timezone fix

---

migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/FinalizeStepConfigRST.java

I am not convinced we are doing the right thing. 
While it is needed, I am not sure if we need to run it with every migrate.
Thoughts?

Added VACUUM to olap migrate.

---

package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/CalpadsSchoolsParser.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentParser.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultPercentileParser.java
package-processor/src/test/resources/CA_schools.csv
package-processor/src/test/resources/percentile/percentiles.csv
package-processor/src/test/resources/pern.csv
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/service/impl/DefaultUpdateOrganizationsService.java
task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/service/impl/UpdateOrganizationServiceTest.java

also use static charset everywhere

make csv parsers consistent wrt comments, blank lines

---

migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/FinalizeStepConfigRST.java

I have also added a blurb to the deployment instructions to set up a task to analyze the redshift database periodically.

remove vacuum and analyze from finalize step

---

import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SbacUser.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/SecurityConfigurer.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/ImportService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/web/GroupController.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/auth/SbacUserTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/web/GroupControllerIT.java

Another small change whilst i avoid the big refactor ... this adds the groups controller, and a method on the import service to deal with file uploads without loading the whole thing into memory.

WIP: add groups controller

---

build.gradle
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/GradeRepositoryIT.java
group-processor/src/test/resources/WarehouseCodesSetup.sql
migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml
migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-olap/src/test/resources/OlapAllCodesSetup.sql
migrate-olap/src/test/resources/OlapCodesPreload.sql
migrate-olap/src/test/resources/OlapEntitiesSetup.sql
migrate-olap/src/test/resources/StagingCodesForDeleteSetup.sql
migrate-olap/src/test/resources/StagingCodesSetup.sql
migrate-olap/src/test/resources/StagingEntitiesSetup.sql
migrate-olap/src/test/resources/WarehouseCodesForDeleteSetup.sql
migrate-olap/src/test/resources/WarehouseCodesSetup.sql
migrate-olap/src/test/resources/WarehouseEntitiesSetup.sql
migrate-olap/src/test/resources/WarehouseEntitiesTeardown.sql
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/resources/ReportingAllCodesSetup.sql
migrate-reporting/src/test/resources/ReportingCodesPreload.sql
migrate-reporting/src/test/resources/StagingCodesForDeleteSetup.sql
migrate-reporting/src/test/resources/StagingCodesSetup.sql
migrate-reporting/src/test/resources/WarehouseCodesForDeleteSetup.sql
migrate-reporting/src/test/resources/WarehouseCodesSetup.sql
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcDepthOfKnowledgeRepositoryIT.java

Added `sequence` to grade table and cut points to Redshift asmt.

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadService.java
group-processor/src/main/resources/application.sql.yml
group-processor/src/test/java/org/opentestsystem/rdw/ingest/group/service/impl/DefaultProcessingLoadServiceIT.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/GroupImportService.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/GroupImportServiceTest.java

Updated this to set filename and success message.

set student group creator

---

build.gradle
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/step/OlapReportingMigrateStepsConfig.java
migrate-olap/src/main/resources/application.staging.to.reporting.sql.yml
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapReportingJobRST.java
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/DeleteEntitiesStepRST.java
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/step/UpsertFactsRST.java
migrate-olap/src/test/resources/OlapAndStagingEntitiesTeardown.sql
migrate-olap/src/test/resources/OlapEntitiesSetup.sql
migrate-olap/src/test/resources/StagingEntitiesSetup.sql

Related to https://github.com/SmarterApp/RDW_Schema/pull/275

Adjusted to match Redshift schema refactoring.

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamSchool.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/DefaultAuthorityService.java
import-service/src/main/resources/application.yml
migrate-common/src/main/resources/application.sql.yml
migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-olap/src/main/resources/application.yml
migrate-olap/src/test/resources/application-redshift.yml
migrate-reporting/src/main/resources/application.yml
migrate-reporting/src/test/resources/application-test.yml

Per discussion this moves some common properties from `app:` to `reporting:`

move properties from "app" to "reporting"

---

build.gradle
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ClaimTarget.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/Exam.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamClaim.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/ExamTarget.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/ClaimTargetRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcAssessmentRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcClaimTargetRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcExamRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java
exam-processor/src/main/resources/application.sql.yml
exam-processor/src/main/resources/application.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ClaimTargetRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryAuditIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessorTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorAuditIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java
exam-processor/src/test/resources/examStudentAudit/trt/B004-SSID001-ICA-030-V03.xml
exam-processor/src/test/resources/examStudentAudit/trt/B005-SSID001-ICA-030-V04.xml
exam-processor/src/test/resources/examStudentAudit/trt/B006-SSID003-ICA-050-V02.xml

I'm still testing ingest with the new data generator output but thought i'd get this up here.

DWR-1722, ingest exam target scores

---

build.gradle

@wtritch any reason we shouldn't do this? I was going to do it in reporting as well.

Update to Camden.SR7

---

build.gradle
common/src/main/java/org/opentestsystem/rdw/ingest/common/config/SbacScoreConfiguration.java
common/src/main/resources/application-ingest-common.yml
exam-processor/src/main/java/config/DataElementsConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/model/DataElement.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultEthnicityService.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/main/java/utils/ExamParserHelper.java
exam-processor/src/main/resources/application.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultEthnicityServiceTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorOptionalDataElementsIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessorRequiredDataElementsIT.java
exam-processor/src/test/resources/TDSReport.iab.emptyDataElements.xml
exam-processor/src/test/resources/TDSReport.iab.noElement.xml
exam-processor/src/test/resources/application-optional.yml
exam-processor/src/test/resources/application-required.yml

Depends on https://github.com/SmarterApp/RDW_Schema/pull/289.

Support for configurable optional student attributes

---

build.gradle
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
exam-processor/src/test/resources/Custom_Subject_ICA.xml
exam-processor/src/test/resources/PreloadCustomSubject.sql
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultAssessmentPackageProcessorIT.java
package-processor/src/test/resources/ELA_subject.xml
package-processor/src/test/resources/Math_subject.xml

I am not sure if this verifies that we do not have anything hardcoded in the ingest.
I did the search and it seems to be fine, but let me know if you think I am missing something.

Verify that Package and Exam ingests support configurable subjects

---

build.gradle
docker-compose.yml
package-processor/src/test/resources/ELA_subject.xml
package-processor/src/test/resources/Math2_subject.xml
package-processor/src/test/resources/Math_subject.xml

Update test subject definitions to new colors.
Update docker-compose to avoid standing up services before config-service is ready.

Update RDW_Common dependency version.

---

build.gradle
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectScorableClaimService.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectScorableClaimServiceTest.java
package-processor/src/test/resources/ELA_subject.xml

https://github.com/SmarterApp/RDW_Schema/pull/318
https://github.com/SmarterApp/RDW_Common/pull/90

RP-84, adjust handling of claim data order

---

CHANGELOG.md
build.gradle
exam-processor/src/main/resources/application.yml
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessorIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/StudentExamProcessorIT.java

remove sessionId from required fields (because ELPAC won't have it)

---

build.gradle
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfig.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/ReportingMigrateJobIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/DeleteEntitiesIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagePackageIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageSubjectsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfigIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertAsmtsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertSubjectsIT.java
migrate-reporting/src/test/resources/ReportingAndStagingEntitiesTeardown.sql
migrate-reporting/src/test/resources/ReportingEntitiesSetup.sql
migrate-reporting/src/test/resources/ReportingSubjectSetup.sql
migrate-reporting/src/test/resources/StagingEntitiesForDeleteSetup.sql
migrate-reporting/src/test/resources/StagingEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql

Most of the changes are to tests and setting up the data for them.

modify migrate-reporting for changes to configurable subjects

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultTDSReportProcessor.java

I think this will fix the build issue. The ExamProcessorIT and ExamProcessorAuditIT  tests pass in TeamCity. I can't figure how, but they do.

RP-283: fixes for Integer cast error. Affects tests only.

---

CHANGELOG.md
build.gradle
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/Authorities.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/auth/StubPermissionService.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/service/DefaultImportService.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/service/DefaultImportServiceTest.java

Since the customer chose not to do the hotfix for this change, i've reworked it a tiny bit for the main develop branch ...

reduce the tenancy chain that is stored with archived payloads

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentGroupRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcStudentRepository.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryAuditIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/ExamRepositoryIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/repository/impl/StudentRepositoryIT.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/TenantConfiguration.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/repository/DataSourceConfiguration.java
migrate-olap/src/main/resources/application.yml
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/TestAppConfig.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/TenantConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/DataSourceConfiguration.java
migrate-reporting/src/main/resources/application.yml
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/TenantConfiguration.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/DataSourceConfiguration.java
task-service/src/main/resources/application.yml

More of the same. This is the last of the datasource changes. Now onto the hard stuff.

add multi-tenant datasource to migrate-olap, migrate-reporting, task-service

---

group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/ArchiveServiceConfiguration.java
group-processor/src/main/resources/application.yml
import-service/src/main/java/org/opentestsystem/rdw/ingest/ArchiveServiceConfiguration.java
import-service/src/main/resources/application.yml
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/ArchiveServiceConfiguration.java
migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-olap/src/main/resources/application.yml
migrate-olap/src/test/resources/application-redshift.yml
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ArchiveServiceConfiguration.java
package-processor/src/main/resources/application.yml

This just replaces the archive configuration, it doesn't really address all the complexities with multi-tenant archiving. I also haven't touched the task service yet.

add multi-tenant archive to ingest services

---

docker-compose.yml
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/impl/JdbcItemTraitRepository.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamItemProcessor.java
exam-processor/src/main/resources/application.yml
migrate-common/src/main/java/org/opentestsystem/rdw/migrate/common/MigrateBatchConfigurer.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/repository/DataSourceConfiguration.java
migrate-olap/src/main/resources/application.yml
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/MigrateReportingApplication.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/DataSourceConfiguration.java
migrate-reporting/src/main/resources/application.yml

With these changes, all the ingest services run without complaining about no-tenant.

get ingest services working without failing due to multi-tenant issues

---

common/src/main/java/org/opentestsystem/rdw/ingest/common/script/PipelineException.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/script/PipelineProcessor.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/script/PipelineType.java
common/src/main/java/org/opentestsystem/rdw/ingest/common/util/TransformedPayloadArchiver.java
common/src/test/java/org/opentestsystem/rdw/ingest/common/util/TransformedPayloadArchiverTest.java
exam-processor/build.gradle
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ExamProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorApplicationIT.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorTransformationTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorValidationTest.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/service/ImportService.java

This will make it easier to integrate pipelines into other processors.

Externalize pipeline functionality

---

exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExternalVendorScriptTest.java
exam-processor/src/test/resources/TDSReport-external-vendor.xml
exam-processor/src/test/resources/scripts/ExternalVendor.groovy

I'm assuming schooIId is in the "schoolId" examinee relationship. Is that a safe assumption? I could duplicate the "best relationship" match if needed, but it would get a bit messy.

Custom script to transform TRTs from external vendor

---

build.gradle
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorTransformationTest.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/ExamProcessorValidationTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/auth/SbacTokenConverterTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/status/DatabaseStatusIndicatorTest.java
import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/web/TestAppConfig.java
migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/MigrateEndpointTest.java
migrate-common/src/test/java/org/opentestsystem/rdw/migrate/common/status/DatabaseStatusIndicatorTest.java
migrate-olap/src/test/java/org/opentestsystem/rdw/ingest/migrate/olap/TestAppConfig.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/AssessmentTransformationTest.java
package-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/status/DatabaseStatusIndicatorTest.java

Since this is just (fairly trivial) changes to tests, i'm going to check it in without PR approval

adjust for latest common

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java

Last piece: integration with ingest services.

RP-601: clear caches on configuration changes

---

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapEnvironmentChangeListener.java

Not really the way I want to do it, but trying to prove why the error is happening.

try running directly

---

build.gradle
common/src/test/resources/application-common-test.yml
docker-compose.yml
exam-processor/src/main/resources/application.yml
group-processor/src/main/resources/application.yml
import-service/src/main/resources/application.yml
import-service/src/test/java/org/opentestsystem/rdw/ingest/impsvc/repository/DataSourceIT.java
import-service/src/test/resources/application-test.yml
migrate-olap/src/main/resources/application.yml
migrate-reporting/src/main/resources/application.yml
package-processor/src/main/resources/application.yml
task-service/src/main/resources/application.yml

setQueryTimeout is not good, remove it. Increase validationInterval from default (3s) to something bigger.

remove any hint of query timeout

---

build.gradle

RP-671 bump common version

---

build.gradle
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/ApplicationConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/config/DataElementsConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/config/TenantConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultExamineeProcessor.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java
exam-processor/src/test/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessorTest.java
exam-processor/src/test/resources/application-test.yml

- use new common ExamProcessorValidationProperties to for tenant aware resolution
- NOTE: will require a common version bump prior to merge

RP-631 exam-processor needs to be made tenant aware of "validation.rewquiredDataElements"

---

build.gradle
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportConfiguration.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportTask.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/status/ReconciliationReportStatusIndicator.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/web/ReconciliationReportEndpoint.java
task-service/src/main/resources/application.yml
task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/ReconciliationReportTaskTest.java
task-service/src/test/java/org/opentestsystem/rdw/ingest/tasking/status/ReconciliationReportStatusIndicatorTest.java

- add resolver to provide default for query

RP-719 task send reconciliation report

---

migrate-olap/src/main/resources/application.warehouse.to.staging.sql.yml
task-service/src/main/resources/application.yml

The optimizer just wasn't dealing with this query. In dev, it went from 1.5h to 12s with this change.

redo query to improve performance

---

import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/repository/DataSourceConfiguration.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/repository/DataSourceConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/DataSourceConfiguration.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/configuration/DataSourceConfiguration.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/DataSourceConfiguration.java

make consistent with other usage in ingest and reporting

add refresh scope to all DataSourceElementResolvers

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/repository/DataSourceConfiguration.java
group-processor/src/main/java/org/opentestsystem/rdw/ingest/group/configuration/DataSourceConfiguration.java
import-service/src/main/java/org/opentestsystem/rdw/ingest/impsvc/repository/DataSourceConfiguration.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/repository/DataSourceConfiguration.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/repository/DataSourceConfiguration.java
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/configuration/DataSourceConfiguration.java
task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/DataSourceConfiguration.java

Following Dave's suggestion to pass beans as parameters rather than making direct calls to the bean creation methods.

Standardized bean creation for DataSources

---

migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/MigrateOlapEventListener.java
migrate-olap/src/main/java/org/opentestsystem/rdw/ingest/migrate/olap/repository/DataSourceConfiguration.java

I will back this out if it is worse in the QA environment

trial fix by re-initializing on refresh before triggered run

---

build.gradle

Make versions and handling consistent between projects

cleanup a couple dependency issues

---

build.gradle
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfig.java
migrate-reporting/src/main/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/WarehouseToStagingStepsConfig.java
migrate-reporting/src/main/resources/application.staging.to.reporting.sql.yml
migrate-reporting/src/main/resources/application.warehouse.to.staging.sql.yml
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageExamIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StageSubjectsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/StagingToReportingStepsConfigIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertExamsIT.java
migrate-reporting/src/test/java/org/opentestsystem/rdw/ingest/migrate/reporting/step/UpsertSubjectsIT.java
migrate-reporting/src/test/resources/ReportingAndStagingEntitiesTeardown.sql
migrate-reporting/src/test/resources/ReportingEntitiesSetup.sql
migrate-reporting/src/test/resources/ReportingSubjectSetup.sql
migrate-reporting/src/test/resources/StagingEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesSetup.sql
migrate-reporting/src/test/resources/WarehouseEntitiesTeardown.sql

The gist of the changes: add migration for subject_trait and exam_trait_score (and the trait_report field added to subject_asmt_type). Most of the changes are in the tests.

migrate subject and exam trait info

---

CHANGELOG.md
build.gradle
package-processor/build.gradle
package-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultSubjectTranslationService.java
package-processor/src/test/resources/ELA_subject.xml
validator/src/test/resources/ELA_subject.xml

this just makes the ELA subject files consistent ... technically not necessary since they are just for tests, but ...

add trait labels; update change log

---

exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/config/TenantConfiguration.java
exam-processor/src/main/java/org/opentestsystem/rdw/ingest/processor/service/impl/DefaultStudentExamProcessor.java

SRS-199: fix for exam processor not getting the lastest validation from config server

SRS-199: fix for exam processor not getting the lastest validation from config server

---

task-service/src/main/java/org/opentestsystem/rdw/ingest/tasking/repository/JdbcReportRepository.java
task-service/src/main/resources/application.sql.yml

Add error rows and result column to distinguish cases.

SRs-468: Reconciliation File customization and specificity - Part 2
